name: CI/CD Pipeline for Node.js Application

on:
  push:
    branches:
      - master  # Triggers workflow when code is pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Update Node.js version if needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional)
      - name: Run tests
        run: npm test

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: docker build -t straykids04/my-nodejs-app .

      # Step 6: Log in to Docker Hub using secrets
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Set the Docker Hub username secret
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Set the Docker Hub password token secret
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      # Step 7: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push straykids04/my-nodejs-app
